/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: sanity/extract.json
export type Language = {
  _id: string;
  _type: 'language';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  id?: string;
  title?: string;
  isActive?: boolean;
  isDefault?: boolean;
  order?: number;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
};

export type Testimonial = {
  _id: string;
  _type: 'testimonial';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  quote?: InternationalizedArrayText;
  author?: string;
  authorRole?: InternationalizedArrayString;
  avatar?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  order?: number;
};

export type SanityImageCrop = {
  _type: 'sanity.imageCrop';
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot';
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type InternationalizedArrayString = Array<
  {
    _key: string;
  } & InternationalizedArrayStringValue
>;

export type InternationalizedArrayText = Array<
  {
    _key: string;
  } & InternationalizedArrayTextValue
>;

export type Experience = {
  _id: string;
  _type: 'experience';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  company?: string;
  short?: InternationalizedArrayString;
  role?: InternationalizedArrayString;
  period?: InternationalizedArrayString;
  description?: InternationalizedArrayText;
  stack?: Array<string>;
  order?: number;
};

export type SkillCategoryReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'skillCategory';
};

export type Skill = {
  _id: string;
  _type: 'skill';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  category?: SkillCategoryReference;
  icon?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  iconDark?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  simpleIconSlug?: string;
  order?: number;
};

export type SkillCategory = {
  _id: string;
  _type: 'skillCategory';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: InternationalizedArrayString;
  key?: string;
  order?: number;
};

export type SkillReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'skill';
};

export type Project = {
  _id: string;
  _type: 'project';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  order?: number;
  featured?: boolean;
  badge?: InternationalizedArrayString;
  description?: InternationalizedArrayText;
  tags?: Array<string>;
  caseType?: InternationalizedArrayString;
  year?: string;
  sub?: InternationalizedArrayText;
  facts?: {
    role?: InternationalizedArrayString;
    timeline?: InternationalizedArrayString;
    stack?: string;
    team?: InternationalizedArrayString;
  };
  caseStudy?: {
    problem?: InternationalizedArrayText;
    role?: InternationalizedArrayText;
    solution?: InternationalizedArrayText;
    outcome?: InternationalizedArrayText;
    metrics?: Array<{
      value?: string;
      label?: InternationalizedArrayString;
      _key: string;
    }>;
  };
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  gallery?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: InternationalizedArrayString;
    _type: 'image';
    _key: string;
  }>;
  githubLink?: string;
  liveLink?: string;
  allowEmbed?: boolean;
  skills?: Array<
    {
      _key: string;
    } & SkillReference
  >;
};

export type Slug = {
  _type: 'slug';
  current?: string;
  source?: string;
};

export type ContactPage = {
  _id: string;
  _type: 'contactPage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  eyebrow?: InternationalizedArrayString;
  heading?: InternationalizedArrayString;
  pitch?: InternationalizedArrayText;
  backLabel?: InternationalizedArrayString;
  subjects?: Array<{
    value?: string;
    label?: InternationalizedArrayString;
    _key: string;
  }>;
  nameLabel?: InternationalizedArrayString;
  namePlaceholder?: InternationalizedArrayString;
  nameError?: InternationalizedArrayString;
  emailLabel?: InternationalizedArrayString;
  emailPlaceholder?: InternationalizedArrayString;
  emailError?: InternationalizedArrayString;
  subjectLabel?: InternationalizedArrayString;
  messageLabel?: InternationalizedArrayString;
  messagePlaceholder?: InternationalizedArrayString;
  messageError?: InternationalizedArrayString;
  requiredLabel?: InternationalizedArrayString;
  sendLabel?: InternationalizedArrayString;
  sendingLabel?: InternationalizedArrayString;
  successTitle?: InternationalizedArrayString;
  successBody?: InternationalizedArrayText;
  errorInvalid?: InternationalizedArrayText;
  errorConfig?: InternationalizedArrayText;
  errorSend?: InternationalizedArrayText;
};

export type HomePage = {
  _id: string;
  _type: 'homePage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: {
    status?: InternationalizedArrayString;
    firstName?: string;
    lastName?: string;
    roleLabel?: InternationalizedArrayString;
    roleStack?: string;
    lede?: InternationalizedArrayText;
    badge?: InternationalizedArrayString;
    photo?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: 'image';
    };
    ctaPrimary?: {
      label?: InternationalizedArrayString;
      href?: string;
    };
    ctaSecondary?: {
      label?: InternationalizedArrayString;
      href?: string;
    };
    marquee?: Array<string>;
  };
  about?: {
    eyebrow?: InternationalizedArrayString;
    lead?: InternationalizedArrayText;
    body?: InternationalizedArrayText;
    whatIDo?: Array<{
      title?: InternationalizedArrayString;
      description?: InternationalizedArrayText;
      _key: string;
    }>;
  };
  workSection?: {
    eyebrow?: InternationalizedArrayString;
    heading?: InternationalizedArrayString;
  };
  skillsSection?: {
    eyebrow?: InternationalizedArrayString;
    heading?: InternationalizedArrayString;
    allLabel?: InternationalizedArrayString;
  };
  experienceSection?: {
    eyebrow?: InternationalizedArrayString;
    heading?: InternationalizedArrayString;
  };
  testimonialsSection?: {
    eyebrow?: InternationalizedArrayString;
    heading?: InternationalizedArrayString;
  };
  contactCta?: {
    eyebrow?: InternationalizedArrayString;
    heading?: InternationalizedArrayString;
    body?: InternationalizedArrayText;
    ctaLabel?: InternationalizedArrayString;
  };
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'sanity.fileAsset';
};

export type SiteSettings = {
  _id: string;
  _type: 'siteSettings';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  brandName?: string;
  location?: InternationalizedArrayString;
  metaTitle?: InternationalizedArrayString;
  metaDescription?: InternationalizedArrayText;
  ogImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  email?: string;
  githubUrl?: string;
  linkedinUrl?: string;
  cvFile?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: 'file';
  };
  cvLabel?: InternationalizedArrayString;
  cvSummary?: InternationalizedArrayText;
  cvEducation?: InternationalizedArrayText;
  navItems?: Array<{
    label?: InternationalizedArrayString;
    target?: string;
    _key: string;
  }>;
  footerTagline?: InternationalizedArrayText;
  copyright?: InternationalizedArrayString;
  getInTouch?: InternationalizedArrayString;
  gotProject?: InternationalizedArrayString;
  code?: InternationalizedArrayString;
  live?: InternationalizedArrayString;
  liveDemo?: InternationalizedArrayString;
  viewCode?: InternationalizedArrayString;
  livePreview?: InternationalizedArrayString;
  openFullscreen?: InternationalizedArrayString;
  allWork?: InternationalizedArrayString;
  backToWork?: InternationalizedArrayString;
  nextProject?: InternationalizedArrayString;
  gallery?: InternationalizedArrayString;
  builtWith?: InternationalizedArrayString;
  requestWalkthrough?: InternationalizedArrayString;
  caseProblem?: InternationalizedArrayString;
  caseRole?: InternationalizedArrayString;
  caseSolution?: InternationalizedArrayString;
  caseOutcome?: InternationalizedArrayString;
  footerNav?: InternationalizedArrayString;
  footerElsewhere?: InternationalizedArrayString;
};

export type InternationalizedArrayTextValue = {
  _type: 'internationalizedArrayTextValue';
  value?: string;
  language?: string;
};

export type InternationalizedArrayStringValue = {
  _type: 'internationalizedArrayStringValue';
  value?: string;
  language?: string;
};

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch';
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: 'sanity.imagePalette';
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions';
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata';
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: 'sanity.fileAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData';
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: 'sanity.imageAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: 'geopoint';
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Language
  | SanityImageAssetReference
  | Testimonial
  | SanityImageCrop
  | SanityImageHotspot
  | InternationalizedArrayString
  | InternationalizedArrayText
  | Experience
  | SkillCategoryReference
  | Skill
  | SkillCategory
  | SkillReference
  | Project
  | Slug
  | ContactPage
  | HomePage
  | SanityFileAssetReference
  | SiteSettings
  | InternationalizedArrayTextValue
  | InternationalizedArrayStringValue
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: sanity/lib/queries.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_type == "siteSettings"][0]{  ...,  "cvUrl": cvFile.asset->url,  "ogUrl": ogImage.asset->url}
export type SITE_SETTINGS_QUERY_RESULT = {
  _id: string;
  _type: 'siteSettings';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  brandName?: string;
  location?: InternationalizedArrayString;
  metaTitle?: InternationalizedArrayString;
  metaDescription?: InternationalizedArrayText;
  ogImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  email?: string;
  githubUrl?: string;
  linkedinUrl?: string;
  cvFile?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: 'file';
  };
  cvLabel?: InternationalizedArrayString;
  cvSummary?: InternationalizedArrayText;
  cvEducation?: InternationalizedArrayText;
  navItems?: Array<{
    label?: InternationalizedArrayString;
    target?: string;
    _key: string;
  }>;
  footerTagline?: InternationalizedArrayText;
  copyright?: InternationalizedArrayString;
  getInTouch?: InternationalizedArrayString;
  gotProject?: InternationalizedArrayString;
  code?: InternationalizedArrayString;
  live?: InternationalizedArrayString;
  liveDemo?: InternationalizedArrayString;
  viewCode?: InternationalizedArrayString;
  livePreview?: InternationalizedArrayString;
  openFullscreen?: InternationalizedArrayString;
  allWork?: InternationalizedArrayString;
  backToWork?: InternationalizedArrayString;
  nextProject?: InternationalizedArrayString;
  gallery?: InternationalizedArrayString;
  builtWith?: InternationalizedArrayString;
  requestWalkthrough?: InternationalizedArrayString;
  caseProblem?: InternationalizedArrayString;
  caseRole?: InternationalizedArrayString;
  caseSolution?: InternationalizedArrayString;
  caseOutcome?: InternationalizedArrayString;
  footerNav?: InternationalizedArrayString;
  footerElsewhere?: InternationalizedArrayString;
  cvUrl: string | null;
  ogUrl: string | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: HOME_QUERY
// Query: *[_type == "homePage"][0]
export type HOME_QUERY_RESULT = {
  _id: string;
  _type: 'homePage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: {
    status?: InternationalizedArrayString;
    firstName?: string;
    lastName?: string;
    roleLabel?: InternationalizedArrayString;
    roleStack?: string;
    lede?: InternationalizedArrayText;
    badge?: InternationalizedArrayString;
    photo?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: 'image';
    };
    ctaPrimary?: {
      label?: InternationalizedArrayString;
      href?: string;
    };
    ctaSecondary?: {
      label?: InternationalizedArrayString;
      href?: string;
    };
    marquee?: Array<string>;
  };
  about?: {
    eyebrow?: InternationalizedArrayString;
    lead?: InternationalizedArrayText;
    body?: InternationalizedArrayText;
    whatIDo?: Array<{
      title?: InternationalizedArrayString;
      description?: InternationalizedArrayText;
      _key: string;
    }>;
  };
  workSection?: {
    eyebrow?: InternationalizedArrayString;
    heading?: InternationalizedArrayString;
  };
  skillsSection?: {
    eyebrow?: InternationalizedArrayString;
    heading?: InternationalizedArrayString;
    allLabel?: InternationalizedArrayString;
  };
  experienceSection?: {
    eyebrow?: InternationalizedArrayString;
    heading?: InternationalizedArrayString;
  };
  testimonialsSection?: {
    eyebrow?: InternationalizedArrayString;
    heading?: InternationalizedArrayString;
  };
  contactCta?: {
    eyebrow?: InternationalizedArrayString;
    heading?: InternationalizedArrayString;
    body?: InternationalizedArrayText;
    ctaLabel?: InternationalizedArrayString;
  };
} | null;

// Source: sanity/lib/queries.ts
// Variable: CONTACT_PAGE_QUERY
// Query: *[_type == "contactPage"][0]
export type CONTACT_PAGE_QUERY_RESULT = {
  _id: string;
  _type: 'contactPage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  eyebrow?: InternationalizedArrayString;
  heading?: InternationalizedArrayString;
  pitch?: InternationalizedArrayText;
  backLabel?: InternationalizedArrayString;
  subjects?: Array<{
    value?: string;
    label?: InternationalizedArrayString;
    _key: string;
  }>;
  nameLabel?: InternationalizedArrayString;
  namePlaceholder?: InternationalizedArrayString;
  nameError?: InternationalizedArrayString;
  emailLabel?: InternationalizedArrayString;
  emailPlaceholder?: InternationalizedArrayString;
  emailError?: InternationalizedArrayString;
  subjectLabel?: InternationalizedArrayString;
  messageLabel?: InternationalizedArrayString;
  messagePlaceholder?: InternationalizedArrayString;
  messageError?: InternationalizedArrayString;
  requiredLabel?: InternationalizedArrayString;
  sendLabel?: InternationalizedArrayString;
  sendingLabel?: InternationalizedArrayString;
  successTitle?: InternationalizedArrayString;
  successBody?: InternationalizedArrayText;
  errorInvalid?: InternationalizedArrayText;
  errorConfig?: InternationalizedArrayText;
  errorSend?: InternationalizedArrayText;
} | null;

// Source: sanity/lib/queries.ts
// Variable: PROJECTS_QUERY
// Query: *[_type == "project"] | order(order asc){    ...,    "skills": skills[]->{ _id, title }  }
export type PROJECTS_QUERY_RESULT = Array<{
  _id: string;
  _type: 'project';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  order?: number;
  featured?: boolean;
  badge?: InternationalizedArrayString;
  description?: InternationalizedArrayText;
  tags?: Array<string>;
  caseType?: InternationalizedArrayString;
  year?: string;
  sub?: InternationalizedArrayText;
  facts?: {
    role?: InternationalizedArrayString;
    timeline?: InternationalizedArrayString;
    stack?: string;
    team?: InternationalizedArrayString;
  };
  caseStudy?: {
    problem?: InternationalizedArrayText;
    role?: InternationalizedArrayText;
    solution?: InternationalizedArrayText;
    outcome?: InternationalizedArrayText;
    metrics?: Array<{
      value?: string;
      label?: InternationalizedArrayString;
      _key: string;
    }>;
  };
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  gallery?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: InternationalizedArrayString;
    _type: 'image';
    _key: string;
  }>;
  githubLink?: string;
  liveLink?: string;
  allowEmbed?: boolean;
  skills: Array<{
    _id: string;
    title: string | null;
  }> | null;
}>;

// Source: sanity/lib/queries.ts
// Variable: PROJECT_QUERY
// Query: *[_type == "project" && slug.current == $slug][0]{    ...,    "skills": skills[]->{ _id, title }  }
export type PROJECT_QUERY_RESULT = {
  _id: string;
  _type: 'project';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  order?: number;
  featured?: boolean;
  badge?: InternationalizedArrayString;
  description?: InternationalizedArrayText;
  tags?: Array<string>;
  caseType?: InternationalizedArrayString;
  year?: string;
  sub?: InternationalizedArrayText;
  facts?: {
    role?: InternationalizedArrayString;
    timeline?: InternationalizedArrayString;
    stack?: string;
    team?: InternationalizedArrayString;
  };
  caseStudy?: {
    problem?: InternationalizedArrayText;
    role?: InternationalizedArrayText;
    solution?: InternationalizedArrayText;
    outcome?: InternationalizedArrayText;
    metrics?: Array<{
      value?: string;
      label?: InternationalizedArrayString;
      _key: string;
    }>;
  };
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  gallery?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: InternationalizedArrayString;
    _type: 'image';
    _key: string;
  }>;
  githubLink?: string;
  liveLink?: string;
  allowEmbed?: boolean;
  skills: Array<{
    _id: string;
    title: string | null;
  }> | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: PROJECT_SLUGS_QUERY
// Query: *[_type == "project" && defined(slug.current)]{ "slug": slug.current }
export type PROJECT_SLUGS_QUERY_RESULT = Array<{
  slug: string | null;
}>;

// Source: sanity/lib/queries.ts
// Variable: SKILLS_QUERY
// Query: *[_type == "skill"] | order(order asc){    ...,    "category": category->{ _id, key, title }  }
export type SKILLS_QUERY_RESULT = Array<{
  _id: string;
  _type: 'skill';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  category: {
    _id: string;
    key: string | null;
    title: InternationalizedArrayString | null;
  } | null;
  icon?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  iconDark?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  simpleIconSlug?: string;
  order?: number;
}>;

// Source: sanity/lib/queries.ts
// Variable: SKILL_CATEGORIES_QUERY
// Query: *[_type == "skillCategory"] | order(order asc)
export type SKILL_CATEGORIES_QUERY_RESULT = Array<{
  _id: string;
  _type: 'skillCategory';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: InternationalizedArrayString;
  key?: string;
  order?: number;
}>;

// Source: sanity/lib/queries.ts
// Variable: EXPERIENCES_QUERY
// Query: *[_type == "experience"] | order(order asc)
export type EXPERIENCES_QUERY_RESULT = Array<{
  _id: string;
  _type: 'experience';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  company?: string;
  short?: InternationalizedArrayString;
  role?: InternationalizedArrayString;
  period?: InternationalizedArrayString;
  description?: InternationalizedArrayText;
  stack?: Array<string>;
  order?: number;
}>;

// Source: sanity/lib/queries.ts
// Variable: TESTIMONIALS_QUERY
// Query: *[_type == "testimonial"] | order(order asc)
export type TESTIMONIALS_QUERY_RESULT = Array<{
  _id: string;
  _type: 'testimonial';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  quote?: InternationalizedArrayText;
  author?: string;
  authorRole?: InternationalizedArrayString;
  avatar?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  order?: number;
}>;

// Query TypeMap
import '@sanity/client';
declare module '@sanity/client' {
  interface SanityQueries {
    '*[_type == "siteSettings"][0]{\n  ...,\n  "cvUrl": cvFile.asset->url,\n  "ogUrl": ogImage.asset->url\n}': SITE_SETTINGS_QUERY_RESULT;
    '*[_type == "homePage"][0]': HOME_QUERY_RESULT;
    '*[_type == "contactPage"][0]': CONTACT_PAGE_QUERY_RESULT;
    '*[_type == "project"] | order(order asc){\n    ...,\n    "skills": skills[]->{ _id, title }\n  }': PROJECTS_QUERY_RESULT;
    '*[_type == "project" && slug.current == $slug][0]{\n    ...,\n    "skills": skills[]->{ _id, title }\n  }': PROJECT_QUERY_RESULT;
    '*[_type == "project" && defined(slug.current)]{ "slug": slug.current }': PROJECT_SLUGS_QUERY_RESULT;
    '*[_type == "skill"] | order(order asc){\n    ...,\n    "category": category->{ _id, key, title }\n  }': SKILLS_QUERY_RESULT;
    '*[_type == "skillCategory"] | order(order asc)': SKILL_CATEGORIES_QUERY_RESULT;
    '*[_type == "experience"] | order(order asc)': EXPERIENCES_QUERY_RESULT;
    '*[_type == "testimonial"] | order(order asc)': TESTIMONIALS_QUERY_RESULT;
  }
}
